storage:
  # Available: sqlite, mariadb, yaml
  type: "sqlite"

  mariadb:
    host: localhost
    port: 3306
    database: db
    username: yov
    password: mysecurepassword

  # Only used for MariaDB
  auto-reconnect: true
