storage:
  # Available: sqlite, mysql, mariadb, yaml
  type: "yaml"

  mysql:
    host: "localhost"
    port: 3306
    database: "yov"
    username: "root"
    password: ""

  # Only used for MySQL/MariaDB
  auto-reconnect: false
